"""
backend/app/seed.py
====================
Loads data/operation_nexus.json (generated by scripts/generate_dataset.py)
into the SQLite database. Idempotent: running twice just re-loads the same
demo state ("Load Demo Investigation").
"""

import json
import os
from .database import init_db, db_cursor

DATA_PATH = os.path.join(os.path.dirname(__file__), "..", "..", "data", "operation_nexus.json")
DATA_PATH = os.path.abspath(DATA_PATH)


def seed_database(reset: bool = True):
    init_db(reset=reset)
    with open(DATA_PATH) as f:
        data = json.load(f)

    with db_cursor() as cur:
        for c in data["cases"]:
            cur.execute(
                "INSERT OR REPLACE INTO cases (id, name, type, status, period_start, period_end, description) "
                "VALUES (?, ?, ?, ?, ?, ?, ?)",
                (c["id"], c["name"], c["type"], c["status"], c["period_start"], c["period_end"], c["description"]),
            )

        def insert_entities(items, etype, name_field="name"):
            for it in items:
                attrs = {k: v for k, v in it.items() if k not in ("id", name_field)}
                cur.execute(
                    "INSERT OR REPLACE INTO entities (id, entity_type, name, attributes) VALUES (?, ?, ?, ?)",
                    (it["id"], etype, it[name_field], json.dumps(attrs)),
                )

        insert_entities(data["persons"], "Person")
        insert_entities(data["phones"], "Phone", name_field="number")
        insert_entities(data["vehicles"], "Vehicle", name_field="make")
        insert_entities(data["locations"], "Location")
        insert_entities(data["organizations"], "Organization")

        for e in data["events"]:
            cur.execute(
                "INSERT OR REPLACE INTO events (id, type, timestamp, location_id, description, case_id) "
                "VALUES (?, ?, ?, ?, ?, ?)",
                (e["id"], e["type"], e["timestamp"], e["location_id"], e["description"], e["case_id"]),
            )

        for ev in data["evidence"]:
            cur.execute(
                "INSERT OR REPLACE INTO evidence (id, type, description, source_record, timestamp, extraction_confidence) "
                "VALUES (?, ?, ?, ?, ?, ?)",
                (ev["id"], ev["type"], ev["description"], ev["source_record"], ev["timestamp"], ev["extraction_confidence"]),
            )

        for r in data["relationships"]:
            cur.execute(
                "INSERT OR REPLACE INTO relationships (id, source, target, type, timestamp, confidence, status, evidence_ids, notes, review_state) "
                "VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)",
                (r["id"], r["source"], r["target"], r["type"], r["timestamp"], r["confidence"], r["status"],
                 json.dumps(r["evidence_ids"]), r.get("notes", ""), "pending"),
            )

    counts = {k: len(data[k]) for k in ("cases", "persons", "phones", "vehicles",
                                         "locations", "organizations", "events",
                                         "evidence", "relationships")}
    return counts


if __name__ == "__main__":
    print(seed_database(reset=True))
